import { Inter } from "next/font/google";
import "./globals.css";
import QueryProviders from "./queryProviders";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ko">
      <body>
        <QueryProviders>{children} </QueryProviders>
      </body>
    </html>
  );
}
